import { NgModule, APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule, Routes } from '@angular/router';
import 'hammerjs';
import { SharedModule } from './core/modules/shared.module';
import { AppComponent } from './app.component';
import { FuseMainModule } from './main/main.module';
import { FuseSplashScreenService } from './core/services/splash-screen.service';
import { FuseConfigService } from './core/services/config.service';
import { FuseNavigationService } from './core/components/navigation/navigation.service';
import { TranslateModule } from '@ngx-translate/core';
import { CustomMatPaginatorIntl } from './core/custom-mat-paginator-intl/custom-mat-paginator-intl';
import { ServiceWorkerModule } from '@angular/service-worker';
import { MatPaginatorIntl } from '@angular/material';
import { environment } from '../environments/environment';
import { PageNoFoundComponent } from './main/content/page-no-found/page-no-found.component';
import { ChartModule } from 'angular2-chartjs';

/* do not edit the line below: autogenerated code */
const appRoutes: Routes = [
  {
    path: 'page-no-found',
    component: PageNoFoundComponent
  },
  {
    path: 'author-collaborations',
    loadChildren: './main/content/author-collaborations/author-collaborations.module#AuthorCollaborationsModule'
  },
  {
    path: 'authors-characterisation',
    loadChildren: './main/content/authors-characterisation/authors-characterisation.module#AuthorsCharacterisationModule'
  },
  {
    path: 'institutions-activity-characterisation',
    loadChildren: './main/content/institutions-activity-characterisation/institutions-activity-characterisation.module#InstitutionsActivityCharacterisationModule'
  },
  {
    path: 'journals-characterisation',
    loadChildren: './main/content/journals-characterisation/journals-characterisation.module#JournalsCharacterisationModule'
  },
  {
    path: 'journals-collaboration',
    loadChildren: './main/content/journals-collaboration/journals-collaboration.module#JournalsCollaborationModule'
  },
  {
    path: '**',
    redirectTo: 'page-no-found'
  }
];

@NgModule({
  declarations: [AppComponent, PageNoFoundComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(appRoutes),
    SharedModule,
    TranslateModule.forRoot(),
    FuseMainModule,
    ServiceWorkerModule.register('/emi/ngsw-worker.js', { enabled: environment.production }),
    ChartModule,
  ],
  providers: [
    {
      provide: MatPaginatorIntl,
      useClass: CustomMatPaginatorIntl
    },
    FuseSplashScreenService,
    FuseConfigService,
    FuseNavigationService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
