import { FuseNavigationModelInterface } from '../core/components/navigation/navigation.model';

export class FuseNavigationModel implements FuseNavigationModelInterface {
    public model: any[];

    constructor() {
        /* do not edit the line below: autogenerated code */
        this.model = [
            {
                "id": "REPORTS",
                "title": "REPORTS",
                "translate": "NAV.REPORTS.self",
                "type": "group",
                "icon": "location_searching",
                "children": [
                        {
                                "id": "AUTHOR_COLLABORATIONS",
                                "title": "Collaboration by Author",
                                "translate": "NAV.REPORTS.AUTHOR_COLLABORATIONS",
                                "type": "item",
                                "url": "/author-collaborations",
                                "icon": "rowing",
                                "priority": 1000,
                                "default": true
                        }
                ],
                "priority": 500
        }
        ];
    }
}
